name: commitlint

on:
  push

permissions:
  contents: read

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # worth noting: this hardcodes the version of commitlint...
      # there is a go package that updates with the repo but i dont know how go works
      - name: Lint most recent commit
        run: |
          echo "Getting commitlint with wget"
          wget https://github.com/conventionalcommit/commitlint/releases/download/v0.12.0/commitlint_v0.12.0_linux_386.tar.gz
          echo "Extracting and Moving commitlint binary to ~/.local/bin"
          tar -vxf commitlint_v0.12.0_linux_386.tar.gz
          mkdir -p ~/.local/bin
          mv ./commitlint ~/.local/bin/commitlint
          echo "Adding /.local/bin to PATH"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          echo "Linting commit"
          commitlint lint --message=${{ github.event.push.head_commit.message }}
