name: commitlint

on:
  push

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # worth noting: this hardcodes the version of commitlint...
      # there is a go package that updates with the repo but i dont know how go works
      - name: Lint most recent commit
        run: |
          wget https://github.com/conventionalcommit/commitlint/releases/download/v0.12.0/commitlint_v0.12.0_linux_386.tar.gz
          tar -xf commitlint_v0.12.0_linux_386.tar.gz
          mv commitlint_v0.12.0_linux_386/commitlint ~/.local/bin/commitlint
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Lint most recent commit (on any push)
        run: commitlint lint --message=${{ github.event.push.head_commit.message }}
